apiVersion: v1
kind: ConfigMap
metadata:
    name: user-service-config
    namespace: planify-dev
data:
    # Server
    SERVER_PORT: "8082"

    # Database
    DB_URL: "jdbc:postgresql://postgres-service:5432/planify"
    DB_SCHEMA: "auth"
    DB_POOL_SIZE: "10"
    DB_POOL_MIN_IDLE: "5"
    DB_CONN_TIMEOUT: "30000"

    # JPA
    JPA_DDL_AUTO: "validate"
    JPA_SHOW_SQL: "false"

    # Keycloak
    KEYCLOAK_URL: "http://keycloak-service:8080"
    KEYCLOAK_REALM: "planify"
    KEYCLOAK_ISSUER_URI: "http://keycloak-service:8080/realms/planify"
    KEYCLOAK_JWK_SET_URI: "http://keycloak-service:8080/realms/planify/protocol/openid-connect/certs"

    # Kafka
    KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
    KAFKA_CONSUMER_GROUP: "user-service"
    KAFKA_AUTO_OFFSET_RESET: "earliest"
    KAFKA_TOPIC_JOIN_REQUESTS: "user.join-requests"
    KAFKA_TOPIC_INVITATIONS: "user.invitations"

    # Flyway
    FLYWAY_ENABLED: "true"

    # Swagger
    SWAGGER_ENABLED: "true"

    # Logging
    LOG_LEVEL_ROOT: "INFO"
    LOG_LEVEL_APP: "INFO"
    LOG_LEVEL_SPRING_WEB: "WARN"
    LOG_LEVEL_SPRING_SECURITY: "WARN"
    LOG_LEVEL_HIBERNATE_SQL: "WARN"

    # Spring Profile
    SPRING_PROFILES_ACTIVE: "prod"
