config:
  springProfilesActive: prod
  jpa:
    showSql: "false"
  swagger:
    enabled: "true"
  management:
    endpointsInclude: "health,info,metrics,prometheus"
  logging:
    levelApp: "INFO"
    levelSpringWeb: "WARN"