{{- if and .Values.ingress.enabled .Values.ingress.enableAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: user-service-basic-auth
type: Opaque
data:
  auth: {{ .Values.ingress.htpasswd | b64enc }}
{{- end }}