{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-external-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.ingress.enableAuth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-service-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Azure Function Access'
    {{- end }}
    {{- if .Values.ingress.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/rate-limit: "100"
    {{- if .Values.ingress.enableTls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.enableTls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: user-service-external-tls
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /external/user-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.service.port }}
  {{- end }}